# Assignment 5
## Austin Peng
## CSC 247

---

# A)

Table gives us conditional distributions.

Make a 16 row table like this:

S SPR R G P(S SPR R G)

0 0 0 0 x
.
.
.

(1 - 0.5)*(1 - 0.7)*(1-0.5)*(1-0.01) = P(S)P(R|S)P(SPR|S)P(G|R, SPR)


Where the final P() is the sum of all conditional probabilities

In [1]:
import random
from pprint import pprint

In [2]:
p_sky=[0.5,0.5]
# cloudy / sunny
p_rain=[0.7, 0.01]
p_sprinkler=[0.5,0.9]
p_grass=[0.99,0.9,0.9,0.01]

In [3]:
# order is sky, rain, spr, grass
# sky 0 == cloudy, sky 1 == sunny
a_combinations=[
    [0,0,0,0],
    [0,0,0,1],
    [0,0,1,0],
    [0,1,0,0],
    [1,0,0,0],
    
    [0,0,1,1],
    [0,1,1,0],
    [1,1,0,0],
    [1,0,1,0],
    [0,1,0,1],
    [1,0,0,1],
    
    [0,1,1,1],
    [1,1,1,0],
    [1,0,1,1],
    [1,1,0,1],
    [1,1,1,1],
]

In [4]:
# finds possibilites for each possible combination
def calc_combinations(combinations):
    for combination in combinations:
        # set sky to cloudy or sunny, 0 or 1
        tempSky = (1-p_sky[0]) if combination[0] == 0 else p_sky[1]
        
        # dependent on sky
        tempRain = p_rain[0] if combination[0] == 0 else p_rain[1]
        tempSprink = p_sprinkler[0] if combination[0] == 0 else p_sprinkler[1]
        
        if int(combination[1]) == 0: tempRain = 1-tempRain
        if int(combination[2]) == 0: tempSprink = 1-tempSprink
    
        # dependent on grass and sprinkler
        if combination[1] == 0 and combination[2] == 0:
            tempGrass = p_grass[3]
        elif combination[1] == 1 and combination[2] == 1:
            tempGrass = p_grass[0]
        elif combination[1] == 1 or combination[2] == 1:
            tempGrass = p_grass[1]
            
        if combination[3] == 0: tempGrass = 1-tempGrass 
        
        total = tempSky*tempRain*tempSprink*tempGrass
        
        a_possibilties.append(round(total,5))

        
    
a_possibilties=[]            
calc_combinations(a_combinations)

print("All conditional probabilities: ")
pprint(a_possibilties)

print("Sum of possibilities: ", sum(a_possibilties) )

All conditional probabilities: 
[0.07425,
 0.00075,
 0.0075,
 0.0175,
 0.049,
 0.0675,
 0.00175,
 5e-05,
 0.04455,
 0.1575,
 0.00049,
 0.17325,
 5e-05,
 0.40095,
 0.00045,
 0.00446]
Sum of possibilities:  1.0


## Discussion:
#### All conditional probabilities listed for each combination. They sum to one so they should be right.

---
# B)

Find joint posterior values where G=0 and G=1

2 Tables with 2^3 probabilities each.

In [5]:
# Combine for easy reading
b_distribution=[]

for x in range(0, len(a_possibilties)):
    temp=a_combinations[x].copy()
    temp.append(a_possibilties[x])
    b_distribution.append(temp)

In [6]:
# Separate into g=1 g=0
gZero=[]
gOne=[]
for x in b_distribution:
    if x[3] == 0:
        gZero.append(x)
    else:
        gOne.append(x)
print("Separate into g=1 and g=0")
pprint(gZero)
print()
pprint(gOne)

Separate into g=1 and g=0
[[0, 0, 0, 0, 0.07425],
 [0, 0, 1, 0, 0.0075],
 [0, 1, 0, 0, 0.0175],
 [1, 0, 0, 0, 0.049],
 [0, 1, 1, 0, 0.00175],
 [1, 1, 0, 0, 5e-05],
 [1, 0, 1, 0, 0.04455],
 [1, 1, 1, 0, 5e-05]]

[[0, 0, 0, 1, 0.00075],
 [0, 0, 1, 1, 0.0675],
 [0, 1, 0, 1, 0.1575],
 [1, 0, 0, 1, 0.00049],
 [0, 1, 1, 1, 0.17325],
 [1, 0, 1, 1, 0.40095],
 [1, 1, 0, 1, 0.00045],
 [1, 1, 1, 1, 0.00446]]


In [7]:
print("Sums of g=0 and g=1:")

gZeroSum=0
for x in gZero:
    gZeroSum+=(x[4])
print(gZeroSum)

gOneSum=0
for x in gOne:
    gOneSum+=(x[4])
print(gOneSum)

Sums of g=0 and g=1:
0.19465
0.80535


In [8]:
# Compute P(S N R | G = 0)
# This is equivalent to dividing each element by the sum of all elements 

gZero_posterior=[]
for x in gZero:
    gZero_posterior.append(round(x[4]/gZeroSum,3))
    
gOne_posterior=[]
for x in gOne:
    gOne_posterior.append(round(x[4]/gOneSum, 3))

print("Posterior Prob. of g=0",)
pprint(gZero_posterior)
print("Sum: ",sum(gZero_posterior),'\n')

print("Posterior Prob. of g=1",)
pprint(gOne_posterior)
print("Sum: ",sum(gOne_posterior))

Posterior Prob. of g=0
[0.381, 0.039, 0.09, 0.252, 0.009, 0.0, 0.229, 0.0]
Sum:  1.0 

Posterior Prob. of g=1
[0.001, 0.084, 0.196, 0.001, 0.215, 0.498, 0.001, 0.006]
Sum:  1.002


In [9]:
for x in range(0, len(gZero)):
    gZero[x].append(gZero_posterior[x])

for x in range(0, len(gOne)):
    gOne[x].append(gOne_posterior[x])


print("S, SPR, R, G, Prob, Posterior Prob")
pprint(gZero)
print()
pprint(gOne)

S, SPR, R, G, Prob, Posterior Prob
[[0, 0, 0, 0, 0.07425, 0.381],
 [0, 0, 1, 0, 0.0075, 0.039],
 [0, 1, 0, 0, 0.0175, 0.09],
 [1, 0, 0, 0, 0.049, 0.252],
 [0, 1, 1, 0, 0.00175, 0.009],
 [1, 1, 0, 0, 5e-05, 0.0],
 [1, 0, 1, 0, 0.04455, 0.229],
 [1, 1, 1, 0, 5e-05, 0.0]]

[[0, 0, 0, 1, 0.00075, 0.001],
 [0, 0, 1, 1, 0.0675, 0.084],
 [0, 1, 0, 1, 0.1575, 0.196],
 [1, 0, 0, 1, 0.00049, 0.001],
 [0, 1, 1, 1, 0.17325, 0.215],
 [1, 0, 1, 1, 0.40095, 0.498],
 [1, 1, 0, 1, 0.00045, 0.001],
 [1, 1, 1, 1, 0.00446, 0.006]]


## Discussion:
#### Probabilities for both tables sum to one.  Values are still similar but there are definate changes in the posterior probabilites.

---
# C)


Use i-1 to draw from previous samples.

for i=1 in range(0, 1000): 

S(i) = P(S | R(i-1), N(i-1), G=0 )

R(i) = P(R | S(i-1), N(i-1), G=0 )

N(i) = P(N | S(i-1), R(i-1), G=0 )


Example:
P(S = 1 | R(i-1), N(i-1), G=0) = 
P(S=1, R(i-1), N(i-1) G=0) / P(S=0, ri-1, ni-1, G=0) + P(S=1, Ri-1, Ni-1, G=0)

Better explanation:
Top part is read from table   /   bottom is the top part + the top part where S=0 or S=1


Use P percent to generate next S value.

In [10]:
import numpy as np
from pprint import pprint

In [11]:
# returns conditional prob given vars
def search_distribution(distribution, sky, sprinkler, rain, grass):
    for x in distribution:
        if x[0]==sky and x[1]==sprinkler and x[2]==rain and x[3]==grass:
            return x[4]

print("Example:", search_distribution(b_distribution, 1,1,1,1))

Example: 0.00446


In [12]:
def find_conditional_probability(sky, sprinkler, rain, grass, change):

    numerator = search_distribution(b_distribution, sky, sprinkler, rain, grass) 
    
    # changes from 0 to 1 and vice versa
    if change==0:
        sky=1-sky

    elif change==1:
        sprinkler=1-sprinkler

    elif change==2:
        rain=1-rain

    
    denominator = numerator + search_distribution(b_distribution, sky , sprinkler, rain, grass)
    
    probability = numerator / denominator
    
    return probability

In [13]:
find_conditional_probability(0, 0, 0, grass=0, change=0)

0.6024340770791075

In [28]:
find_conditional_probability(1, 1, 1, grass=1, change=0)

0.025097068257273092

## Run Gibbs

In [14]:
# Will be 1000x3 Table for Sky, Sprinkler, and Rain
# Base case of 0, 0, 0
c_Gibbs_samples_gZero=[ [0],[0],[0] ]
c_Gibbs_samples_gOne=[ [0],[0],[0] ]

In [15]:
# Part C
# g=0
trials=10000
for i in range(1, trials):
    count=0
    for var in c_Gibbs_samples_gZero:
        
        # sky, sprinkler, rain, grass
        # uses -1 index to take the latest value
        
        # CHANGES HERE
        p = find_conditional_probability( c_Gibbs_samples_gZero[0][-1], c_Gibbs_samples_gZero[1][-1], c_Gibbs_samples_gZero[2][-1], 0, count)
        
        value = np.random.binomial(1, p, 1) # number of trials, probability of each trial, num of outputs
        var.append(int(value))
        count+=1

# g=1
for i in range(1, trials):
    count=0
    for var in c_Gibbs_samples_gOne:
        
        # sky, sprinkler, rain, grass
        # uses -1 index to take the latest value
        p = find_conditional_probability( c_Gibbs_samples_gOne[0][-1], c_Gibbs_samples_gOne[1][-1], c_Gibbs_samples_gOne[2][-1], 1, count)
        value = np.random.binomial(1, p, 1) # number of trials, probability of each trial, num of outputs
        var.append(int(value))
        count+=1

## Evaluate Results

In [16]:
# rearrange lists to check accuracy
# create list to hold n combinations
reformated_Gibbs_gZero=[]
for x in range(0, len(c_Gibbs_samples_gZero[0])):
    reformated_Gibbs_gZero.append([])
    
reformated_Gibbs_gOne=[]
for x in range(0, len(c_Gibbs_samples_gOne[0])):
    reformated_Gibbs_gOne.append([])

len(reformated_Gibbs_gOne)

10000

In [17]:
# fill g=0 with Gibbs values
for var_list in c_Gibbs_samples_gZero:
    for x in range(0, len(var_list)):
        reformated_Gibbs_gZero[x].append(var_list[x])

# fill g=1
for var_list in c_Gibbs_samples_gOne:
    for x in range(0, len(var_list)):
        reformated_Gibbs_gOne[x].append(var_list[x])

In [18]:
# assemble list of combinations to check accuracy
gZero_combinations=[]
for x in gZero:
    gZero_combinations.append([x[0],x[1],x[2],x[3] ])
    
    
gOne_combinations=[]
for x in gOne:
    gOne_combinations.append([x[0],x[1],x[2],x[3] ])

pprint(gOne_combinations)

[[0, 0, 0, 1],
 [0, 0, 1, 1],
 [0, 1, 0, 1],
 [1, 0, 0, 1],
 [0, 1, 1, 1],
 [1, 0, 1, 1],
 [1, 1, 0, 1],
 [1, 1, 1, 1]]


In [19]:
# check # of occurences for each combinationand divide by total
gibbs_results_gZero=[]

for combination in gZero_combinations: 
    count=0
    for x in reformated_Gibbs_gZero:
        if x[0]==combination[0] and x[1]==combination[1] and x[2]==combination[2]:
            count+=1

    gibbs_results_gZero.append(count/len(reformated_Gibbs_gOne))

    
gibbs_results_gOne=[]

for combination in gOne_combinations: 
    count=0
    for x in reformated_Gibbs_gOne:
        if x[0]==combination[0] and x[1]==combination[1] and x[2]==combination[2]:
            count+=1

    gibbs_results_gOne.append(count/len(reformated_Gibbs_gOne))

In [20]:
# results!

pprint(gibbs_results_gZero)
pprint(gibbs_results_gOne)

[0.1254, 0.1238, 0.1261, 0.1245, 0.1231, 0.1255, 0.1265, 0.1251]
[0.123, 0.1348, 0.1171, 0.1273, 0.1272, 0.1264, 0.1159, 0.1283]


In [21]:
print("Results from B\n")
print("S, SPR, R, G, Prob, Posterior Prob")
pprint(gZero)
print()
pprint(gOne)

Results from B

S, SPR, R, G, Prob, Posterior Prob
[[0, 0, 0, 0, 0.07425, 0.381],
 [0, 0, 1, 0, 0.0075, 0.039],
 [0, 1, 0, 0, 0.0175, 0.09],
 [1, 0, 0, 0, 0.049, 0.252],
 [0, 1, 1, 0, 0.00175, 0.009],
 [1, 1, 0, 0, 5e-05, 0.0],
 [1, 0, 1, 0, 0.04455, 0.229],
 [1, 1, 1, 0, 5e-05, 0.0]]

[[0, 0, 0, 1, 0.00075, 0.001],
 [0, 0, 1, 1, 0.0675, 0.084],
 [0, 1, 0, 1, 0.1575, 0.196],
 [1, 0, 0, 1, 0.00049, 0.001],
 [0, 1, 1, 1, 0.17325, 0.215],
 [1, 0, 1, 1, 0.40095, 0.498],
 [1, 1, 0, 1, 0.00045, 0.001],
 [1, 1, 1, 1, 0.00446, 0.006]]


In [22]:
# for comparison
print("Gibbs is on Left, Correct on Right \n\nG=0")
for x in range(0,8):
    print(gibbs_results_gZero[x], "  ",round(gZero[x][5], 3))

print()
print("G1")
for x in range(0,8):
    print(gibbs_results_gOne[x], "  ",round(gOne[x][5], 3))

Gibbs is on Left, Correct on Right 

G=0
0.1254    0.381
0.1238    0.039
0.1261    0.09
0.1245    0.252
0.1231    0.009
0.1255    0.0
0.1265    0.229
0.1251    0.0

G1
0.123    0.001
0.1348    0.084
0.1171    0.196
0.1273    0.001
0.1272    0.215
0.1264    0.498
0.1159    0.001
0.1283    0.006


## Discussion:
#### Gibbs values are a lot more evenly distributed for each combination compared to the posterior values. Increasing the # of trials up to 10000 and 5000 from 1000 did not really change anything.

---
# D)

corcoef( S (1000x1), S (1000x1) )


## Correlation between G=0 and G=1 samples generated by Gibbs

In [23]:
print("For Variable Sky:")
print(np.corrcoef(c_Gibbs_samples_gZero[0], c_Gibbs_samples_gOne[0]))

print("\nFor Variable Sprinkler:")
print(np.corrcoef(c_Gibbs_samples_gZero[1], c_Gibbs_samples_gOne[1]))

print("\nFor Variable Rain:")
print(np.corrcoef(c_Gibbs_samples_gZero[2], c_Gibbs_samples_gOne[2]))

For Variable Sky:
[[ 1.         -0.00138658]
 [-0.00138658  1.        ]]

For Variable Sprinkler:
[[ 1.         -0.00421031]
 [-0.00421031  1.        ]]

For Variable Rain:
[[ 1.         -0.00110042]
 [-0.00110042  1.        ]]


## Correlation between Samples of different Variables

In [24]:
print("For Sky vs Sprinkler:")
print(np.corrcoef(c_Gibbs_samples_gZero[0], c_Gibbs_samples_gZero[1]))

print("\nFor Sky vs Rain:")
print(np.corrcoef(c_Gibbs_samples_gZero[0], c_Gibbs_samples_gZero[2]))

print("\nFor Sprinkler vs Rain:")
print(np.corrcoef(c_Gibbs_samples_gZero[1], c_Gibbs_samples_gZero[2]))

For Sky vs Sprinkler:
[[ 1.00000000e+00 -3.98722073e-04]
 [-3.98722073e-04  1.00000000e+00]]

For Sky vs Rain:
[[1.         0.00620966]
 [0.00620966 1.        ]]

For Sprinkler vs Rain:
[[ 1.         -0.00380122]
 [-0.00380122  1.        ]]


## Correlation between posterior results from B) and gibbs generated results

In [25]:
print("For G=0:")
print(np.corrcoef(gibbs_results_gZero,gZero_posterior))

print("\nFor G=1:")
print(np.corrcoef(gibbs_results_gOne,gOne_posterior))

For G=0:
[[1.         0.35006042]
 [0.35006042 1.        ]]

For G=1:
[[1.         0.06015245]
 [0.06015245 1.        ]]


## Discussion:

The Correlation Coefficient Matrix is a measure of the direction and strength of a linear relationships among variables. The coefficient range is from -1 to 1 where 1 is a perfect positive relationship, -1 is a perfect negative relationship and 0 means no relationship.

### 1

For the first comparison we can see that there is no correlation between Sky and Rain when comparing values from g=0 and g=1. However there is a strong negative correlation between the Sprinkler Variable.


### 2

The second comparison shows us that there is no correlation between any of the 3 other variables when g=0


### 3

When comparing the posterior probabilities, both are negatively correlated. Where g=0, there is weak correlation but for g=1 there is a semi strong correlation of -0.34.


---

# E) RESULTS ON SEPERATE DOCUMENT

Change the probabilities for Sky to something closer to 1 and 0. Ex: (0.1, 0.9)